apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g81fv8wnb-python
  janus-idp.io/tekton: g81fv8wnb-python
  backstage.io/kubernetes-id: g81fv8wnb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g81fv8wnb-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
